### ISSUE TITLE
hi problem download

### ISSUE THREAD

**Issue by oremic** [funnybrum/PowerMonitor#1]
lab$ git clone git@github.com:funnybrum/esp8266-base.git
Cloning into 'esp8266-base'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by funnybrum** [comment]
Use "git clone https://github.com/funnybrum/esp8266-base.git" instead.

I'll update the documentation shortly.
